services:
  calendar_bot:
    build: .
    container_name: calendar_bot-calendar_bot-1
    restart: unless-stopped
    dns:
      - 192.168.50.218
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
      - /home/joel/my_super_secure_secrets:/app/secrets
      - /home/joel/my_super_secure_secrets/google_auth:/app/common/auth:ro
      - ./common:/app/common
      - ./utils:/app/utils
      - ./gunicorn_config.py:/app/gunicorn_config.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - default
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  cloudflared_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: calendar_bot-cloudflared_tunnel-1
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    dns:
      - 192.168.50.218
      - 1.1.1.1
      - 8.8.8.8
    depends_on:
      calendar_bot:
        condition: service_healthy

  health_monitor:
    build:
      context: .
      dockerfile: monitor_bot_health/Dockerfile.monitor
    container_name: calendar_bot-health_monitor-1
    restart: unless-stopped
    volumes:
      - ./monitor_status:/app/status
      - /home/joel/my_super_secure_secrets:/app/secrets
      - ./common:/app/common
      - ./utils:/app/utils
    depends_on:
      calendar_bot:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

networks:
  monitoring:
    external: true
    name: homelab-monitoring_monitoring_net
