services:
  calendar_bot:
    build: .
    container_name: calendar_bot-calendar_bot-1
    restart: unless-stopped
    environment:
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - TO_EMAIL=${TO_EMAIL}
      - UPTIME_KUMA_PUSH_URL=${UPTIME_KUMA_PUSH_URL}
      - GOOGLE_WEBHOOK_URL=${GOOGLE_WEBHOOK_URL}
    volumes:
      - ./data:/app/data
      - /home/joel/my_super_secure_secrets:/app/secrets
      - /home/joel/my_super_secure_secrets/google_auth:/app/common/auth
      - ./utils:/app/utils
      - ./gunicorn_config.py:/app/gunicorn_config.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - backend_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  backend_net:
    external: true
    name: homelab_backend
